@include("landingPage.components.head")
@include("landingPage.components.spinner")
@include("landingPage.components.topbar")
@include("landingPage.components.navbar")
@include("landingPage.components.hero")
@include("landingPage.components.about")
@include("landingPage.components.services")
@include("landingPage.components.blog")
@include("landingPage.components.destination")
@include("landingPage.components.explore")
@include("landingPage.components.blogs")
@include("landingPage.components.gallery")
@include("landingPage.components.booking")
@include("landingPage.components.testimonial")
@include("landingPage.components.subscribe")
@include( "landingPage.components.footer")
