@include("landingPage.components.head")
@include("landingPage.components.spinner")
@include("landingPage.components.topbar")
@include("landingPage.components.navbar")
@include("landingPage.components.hero")
@include("landingPage.components.about")
@include("landingPage.components.blog")
@include("landingPage.components.explore")
@include("landingPage.components.blogs")
@include("landingPage.components.testimonial")
@include( "landingPage.components.footer")
