@include("landingPage.components.head")
@include("landingPage.components.spinner")
@include("landingPage.components.topbar")
@include("landingPage.components.navbar")
@include("landingPage.components.hero")
@include("landingPage.components.check_product")
@include("landingPage.components.services")
@include("landingPage.components.blogs")
@include("landingPage.components.recipes")
@include("landingPage.components.success_story")
@include("landingPage.components.testimonial")

@include("landingPage.components.caption")
@include( "landingPage.components.footer")
